apiVersion: v1
kind: Service
metadata:
  name: stock-analyzer-service
spec:
  selector:
    app: stock-analyzer
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 5000 
  type: LoadBalancer 