apiVersion: v1
kind: Service
metadata:
  name: stock-analyzer-service
spec:
  selector:
    app: stock-analyzer
  ports:
    - protocol: TCP
      port: 80       # External port clients will connect to
      targetPort: 5000 # Internal port of your container
  type: LoadBalancer # Creates a cloud load balancer to direct traffic to your app